---
- name: Transfer list of seeds
  copy: src=seeds.txt dest={{ code_data }}/seeds.txt

- name: Launch query-fetching job
  command: >
    {{ projectdir }}/venv/bin/python
    {{ src }}/fetch/queries/fetch_queries.py
    {{ code_data }}/seeds.txt
    --db postgres
    --db-config {{ src }}/{{ postgres_config }}
  async: "{{ long_time }}"
  poll: 0
  register: fetcher_sleeper

- name: Fail if job already exited.  If failure, this job may already be running.
  async_status: jid={{ fetcher_sleeper.ansible_job_id }}
  register: job_result
  failed_when: job_result.finished
  retries: 1
